name: Build Geode Mod
on:
  workflow_dispatch:
  push:
    branches:
      - "**"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows
          os: windows-latest

    name: Build ${{ matrix.config.name }}
    uses: geode-sdk/build-action/.github/workflows/build.yml@v2
    with:
      os: ${{ matrix.config.os }}
